config/routes.rb
Rails.application.routes.draw do

	root 'homepage#index'

	match '/auth/:provider/callback', to: 'users#login', via: [:get, :post]
	get '/logout', to: 'users#logout' # TODO: move to delete method

	resource :user, only: [:show, :update] do
		member do
			post 'setup'
			post 'reset_password'
		end
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	def session
		{
			id: id
		}
	end

	def has_account?
		account_name != nil
	end

	def title
		has_account? ? account_name : email
	end

	def self.from_omni(info)
		return find_or_create_by uid: info.uid do |u|
			u.email = info.info.email
		end
	end

	def self.from_session(info)
		return find_by! id: info['id']
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def auth_user
		if session[:user] == nil
			redirect_to '/auth/nas_auth'
			return nil
		end
		@user = User.from_session session[:user]
	end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/users_controller.rb
require 'server_io'

class UsersController < ApplicationController
	skip_before_action :verify_authenticity_token, only: :login

	def login
		@user = User.from_omni request.env['omniauth.auth']
		session[:user] = @user.session
		redirect_to user_path
	end

	def logout
		session[:user] = nil
		redirect_to '/'
	end

	def show
		auth_user
	end

	def reset_password
		return unless verify_user_status true

		password = random_password
		io = ServerIO::ServerIO.new
		io.set_password @user.account_name, password
		io.exec!
		redirect_to user_path, notice: 'Your temporary password is ' + password
	end

	def setup
		return unless verify_user_status false

		username = params[:create][:username]
		password = random_password

		io = ServerIO::ServerIO.new
		io.create_user username
		io.set_password username, password

		if /^[a-z]*$/.match username
			@user.account_name = username
			@user.transaction do
				@user.save!
				io.exec!
			end
			redirect_to user_path, notice: 'Your account has been created. Your temporary password is ' + password
		else
			redirect_to user_path, alert: 'Your username must only contain lower case letters.'
		end
	end

	private
	def random_password
		[*('a'..'z'), *('0'..'9')].shuffle[0, 16].join
	end

	def verify_user_status(registered)
		return unless auth_user
		if @user.has_account? != registered
			redirect_to '/'
			return false
		end
		true
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		return nil if session[:user] == nil
		User.from_session session[:user]
	end
end

app/views/homepage/index.html.erb
Hello, world!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NASSrv</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
	<% if current_user == nil %>
			<%= link_to 'Dev Auth', '/auth/developer' unless Rails.env.production? %>
			<%= link_to 'NAS-Auth', '/auth/nas_auth' %>
	<% else %>
			<%= link_to current_user.title, user_path %>
			<%= link_to 'Logout', '/logout' %>
	<% end %>
</header>
<% flash.each do |key, value| %>
		<%= content_tag :div, class: ['alert', 'alert-' + key] do %>
				<%= value %>
		<% end %>
<% end %>
<%= yield %>
</body>
</html>

app/views/users/show.html.erb
<% if current_user.has_account? %>
		You have an account.<br/>
		<h2>Connecting to your account</h2>
		<p>To use your account, go to Go to <a href="https://znix.xyz/vm/shell/">https://znix.xyz/vm/shell/</a></p>
		<%= link_to 'Reset Password', reset_password_user_path,
								method: :post,
								data: { confirm: 'Are you sure?' } %>
<% else %>
		<%= form_for :create, url: setup_user_path, method: :post do |f| %>
				<p>Please pick a username carefully, as it cannot be easily changed.</p>

				<p>
					<%= f.label :username %><br>
					<%= f.text_field :username %>
				</p>

				<p>
					<%= f.submit %>
				</p>
		<% end %>
<% end %>